[project]
name = "pathogenic-variants-allofus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.15.5",
    "polars>=1.33.1",
    "watchdog>=6.0.0",
]
